import { GeoJSONMultiPolygon, GeoJSONPolygon } from './index';
export declare function isNumber(value: any): value is number;
export declare function createError(message: string): Error;
export declare function checkTileUrl(url: string | Array<string>): Array<string>;
export declare const CANVAS_ERROR_MESSAGE: Error;
export declare function lnglat2Mercator(coordinates: Array<number>): number[];
export declare const FetchCancelError: Error;
export declare const FetchTimeoutError: Error;
export declare function isPolygon(feature: GeoJSONPolygon | GeoJSONMultiPolygon): boolean;
export declare function isEPSG3857(projection: string): projection is "EPSG:3857";
